const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event34_Act1,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event35_Act3,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event36_Act3,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{planoDeFundo: 0},
	{Sólido: 0},
	{pisoDeCantoDireito: 0},
	{pisoDosMeios: 0},
	{rampadepedregulho: 0},
	{Fixar: 0},
	{RestritoAoLayout: 0},
	{Spriteninjapreto: 0},
	{Plataforma: 0},
	{p1: 0},
	{CentrarEm: 0},
	{camerap1: 0},
	{p2: 0},
	{Teclado: 0},
	{SpriteNinjaBranco: 0},
	{telaDeInicio: 0},
	{Mouse: 0},
	{campanha: 0},
	{pisoDePedregulho: 0},
	{rampaDePedregulho2: 0},
	{pisoSecoComArbusto: 0},
	{primeiroPisoSeco: 0},
	{rampaSeca: 0},
	{blocoFicoSeco: 0},
	{rampaInvertidaSeca: 0},
	{plataformas: 0},
	{postes: 0},
	{arbusto: 0},
	{bambu: 0},
	{pisoSeco: 0},
	{Áudio: 0},
	{pisoPedregulho: 0},
	{pedregullhos: 0},
	{portal: 0},
	{lampada: 0},
	{spinhos1: 0},
	{Sprite15: 0},
	{teleporte: 0},
	{ação: 0},
	{inimigo: 0},
	{marcador: 0},
	{contrato: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{kunai: 0},
	{varialContratos: 0},
	{contrato2: 0},
	{Sprite: 0},
	{variavelVidas: 0},
	{placaDeMadeira: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{voceMorreu: 0},
	{reiniciar: 0},
	{JOGAR: 0},
	{JOGARNOVAMENTE: 0},
	{Sprite5: 0},
	{Texto: 0},
	{contratos: 0},
	{Vidas: 0}
];

self.InstanceType = {
	planoDeFundo: class extends self.ITiledBackgroundInstance {},
	pisoDeCantoDireito: class extends self.ISpriteInstance {},
	pisoDosMeios: class extends self.ISpriteInstance {},
	rampadepedregulho: class extends self.ISpriteInstance {},
	Spriteninjapreto: class extends self.ISpriteInstance {},
	p1: class extends self.ISpriteInstance {},
	camerap1: class extends self.ISpriteInstance {},
	p2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	SpriteNinjaBranco: class extends self.ISpriteInstance {},
	telaDeInicio: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	campanha: class extends self.IButtonInstance {},
	pisoDePedregulho: class extends self.ISpriteInstance {},
	rampaDePedregulho2: class extends self.ISpriteInstance {},
	pisoSecoComArbusto: class extends self.ISpriteInstance {},
	primeiroPisoSeco: class extends self.ISpriteInstance {},
	rampaSeca: class extends self.ISpriteInstance {},
	blocoFicoSeco: class extends self.ISpriteInstance {},
	rampaInvertidaSeca: class extends self.ISpriteInstance {},
	plataformas: class extends self.ISpriteInstance {},
	postes: class extends self.ISpriteInstance {},
	arbusto: class extends self.ISpriteInstance {},
	bambu: class extends self.ISpriteInstance {},
	pisoSeco: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	pisoPedregulho: class extends self.ISpriteInstance {},
	pedregullhos: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	lampada: class extends self.ISpriteInstance {},
	spinhos1: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	teleporte: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	contrato: class extends self.ISpriteInstance {},
	kunai: class extends self.ISpriteInstance {},
	varialContratos: class extends self.ITextInstance {},
	contrato2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	variavelVidas: class extends self.ITextInstance {},
	placaDeMadeira: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	voceMorreu: class extends self.ITextInstance {},
	reiniciar: class extends self.IButtonInstance {},
	JOGAR: class extends self.IButtonInstance {},
	JOGARNOVAMENTE: class extends self.IButtonInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {}
}